// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

MeIR ir;
MeDCMotor motor_9(9);
MeDCMotor motor_10(10);
MeBuzzer buzzer;

float x = 0;
float d = 0;

void move(int direction, int speed) {
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(direction == 1) {
    leftSpeed = speed;
    rightSpeed = speed;
  } else if(direction == 2) {
    leftSpeed = -speed;
    rightSpeed = -speed;
  } else if(direction == 3) {
    leftSpeed = -speed;
    rightSpeed = speed;
  } else if(direction == 4) {
    leftSpeed = speed;
    rightSpeed = -speed;
  }
  motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
  motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  ir.begin();
  x = 0;
  d = 0;
  while(1) {
      if(ir.keyPressed(64)){
          x = 70;
          d = 0;

      }
      if(ir.keyPressed(25)){
          x = 70;
          d = 1;

      }
      if(ir.keyPressed(7)){
          x = 70;
          d = 2;

      }
      if(ir.keyPressed(9)){
          x = 70;
          d = 3;

      }
      if(d == 0.000000){

          move(1, x / 100.0 * 255);

      }
      if(d == 1.000000){

          move(2, x / 100.0 * 255);

      }
      if(d == 2.000000){

          move(3, x / 100.0 * 255);

      }
      if(d == 3.000000){

          move(4, x / 100.0 * 255);

      }
      if(x > 0){
          x += -0.1;

      }
      if(ir.keyPressed(12)){

          buzzer.tone(262, 0.25 * 1000);
          _delay(0.02);

      }
      if(ir.keyPressed(24)){

          buzzer.tone(294, 0.25 * 1000);
          _delay(0.02);

      }
      if(ir.keyPressed(94)){

          buzzer.tone(330, 0.25 * 1000);
          _delay(0.02);

      }
      if(ir.keyPressed(8)){

          buzzer.tone(349, 0.25 * 1000);
          _delay(0.02);

      }
      if(ir.keyPressed(28)){

          buzzer.tone(392, 0.25 * 1000);
          _delay(0.02);

      }
      if(ir.keyPressed(90)){

          buzzer.tone(440, 0.25 * 1000);
          _delay(0.02);

      }
      if(ir.keyPressed(66)){

          buzzer.tone(494, 0.25 * 1000);
          _delay(0.02);

      }

      _loop();
  }

}

void _loop() {
  ir.loop();
}

void loop() {
  _loop();
}

